version: '3.8'

services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myapp
    restart: unless-stopped
    ports:
      - "8080:8080"  # Adjust to your app's port
    environment:
      - GO_ENV=production
      # Add other env vars or use env_file
    networks:
      - app-network

networks:
  app-network:
    driver: bridge